[package]
name = "rtc"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rtc"
path = "src/main.rs"

[dependencies]
rand = "0.9.1"
clap = { version = "4.5", features = ["derive"] }
dirs = "6.0.0"
hex-wrapper = "1.5.2"
